language: c
sudo: required
git:
  depth: 6

env:
  global:
    - CC=gcc-8
    - FC=gfortran-8
    
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install cmake
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc  
  - sudo apt-get -y install gfortran-8
  - sudo apt-get -y install libnetcdfc7 
  - sudo apt-get -y install libnetcdf-dev
  - sudo apt-get -y install findutils
  - sudo updatedb --add-prunepaths '/bin /opt'
  - ls -la

script:
  - cd $TRAVIS_BUILD_DIR/build/linux_x64/gfortran
  - ./run_cmake_gfortran.sh
  - make
