language: c
sudo: required
git:
  depth: 3

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install cmake
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc  
  - sudo apt-get -y install gfortran-8
  - sudo apt-get install libnetcdf13 libnetcdf-cdv
  - sudo apt-get -y install findutils
  - sudo updatedb --localpaths='/usr'
  - ls -la

script:
  - cd build/linux_x64/gfortran
  - ./run_cmake_gfortran.sh
  - make
