language: c
dist: xenial
sudo: required
compiler: gcc-6
git:
  depth: 6

env:
  global:
    - CC=gcc-6
    - FC=gfortran-6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install cmake
  - sudo apt-get -y install gfortran-6
  - sudo apt-get -y install libnetcdf11
  - sudo apt-get -y install libhdf5-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libnetcdf.so.11 /usr/lib/x86_64-linux-gnu/libnetcdf.so
  - ls -la

script:
  - cd $TRAVIS_BUILD_DIR/build/linux_x64/gfortran
  - ./run_cmake_gfortran.sh
  - make
  - make copy
  - cd $TRAVIS_BUILD_DIR/test/unit_tests
  - ./swbtest
