language: c
dist: bionic
sudo: required
compiler: gcc-8
git:
  depth: 3

env:
  global:
    - CC=gcc-8
    - FC=gfortran-8

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install cmake
  - sudo apt-get -y install gfortran-8
  - sudo apt-get -y install libnetcdf-dev
  - sudo apt-get -y install libhdf5-dev
  - ls -la

script:
  - cd $TRAVIS_BUILD_DIR/build/linux_x64/gfortran
  - ./run_cmake_gfortran__gcc-8.sh
  - make
  - make copy
  - cd $TRAVIS_BUILD_DIR/test/unit_tests
  - ./swbtest
