language: c
dist: xenial
sudo: required
compiler: gcc-6
git:
  depth: 6

env:
  global:
    - CC=gcc-6
    - FC=gfortran-6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install cmake
  - sudo apt-get -y install gfortran-6
  - sudo apt-get -y install libnetcdf11
  - sudo apt-get -y install libhdf5-dev
  - sudo apt-get -y install findutils
  - sudo updatedb --add-prunepaths '/bin /opt'
  - ls -la

script:
  - cd $TRAVIS_BUILD_DIR/build/linux_x64/gfortran
  - ./run_cmake_gfortran.sh
  - make
