language: c
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install cmake
  - sudo apt-get -y install gcc-8
  - sudo apt-get -y install gfortran-8
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - tree

script:
  - cd build/linux_x64_/gfortran
  - ./run_cmake_gfortran.sh
  - make
